language: csharp
solution: sln/GCM.NET.sln
env:
  global:
    - COMMIT: $TRAVIS_COMMIT
    - BUILD_NUMBER: $TRAVIS_BUILD_NUMBER
mono:
- latest
before_install:
- git submodule update --init --recursive
script:
- xbuild /p:Configuration=Release sln/GCM.NET.sln
